version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: contactos-turisticos-db
    environment:
      POSTGRES_DB: contactos_turisticos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    container_name: contactos-turisticos-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

  adminer:
    image: adminer
    container_name: contactos-turisticos-adminer
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge